# Generated by Django 5.1.6 on 2026-03-11 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('machine_type', models.CharField(choices=[('ac_large', 'Large AC'), ('ac_small', 'Small AC'), ('fan', 'Ventilation Fan')], max_length=20)),
                ('zone', models.CharField(max_length=128)),
                ('rated_power_kw', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AIDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('action_type', models.CharField(max_length=32)),
                ('action_value', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_decisions', to='hvac.machine')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='hvac_aideci_timesta_65c6dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('power_kw', models.FloatField(default=0)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('setpoint_c', models.FloatField(blank=True, null=True)),
                ('speed_percent', models.FloatField(blank=True, null=True)),
                ('is_on', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='hvac.machine')),
            ],
            options={
                'indexes': [models.Index(fields=['machine', 'timestamp'], name='hvac_sensor_machine_7867ad_idx'), models.Index(fields=['timestamp'], name='hvac_sensor_timesta_f962ff_idx')],
            },
        ),
    ]
